version: "2"
services:

  mysql:
    image: mysql:5.6
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: rootwolf
        MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ~/Github/Vulnerability-goapp/runenv/mysql:/etc/mysql 
    container_name: vulnapp-mysql

  goapp:
    image: golang:1.13-alpine3.10
    ports:
      - 9090:9090
    volumes:
      - ~/Github/Vulnerability-goapp:/goapp
    working_dir: /goapp
    command: sh ./runenv/Devbuildaemon.sh
    depends_on:
      - mysql
    container_name: vulnapp-goapp
