version: "2"
services:

  db:
    image: mysql:5.6
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: rootwolf
        MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ~/Github/Vulnerability-goapp/mysql/mysql.conf:/etc/mysql/mysql.conf:rw 

  goapp:
    image: golang:1.13-alpine3.10
    ports:
      - 9090:9090
    volumes:
      - ~/Github/Vulnerability-goapp:/goapp
    working_dir: /goapp
    command: go run main.go
    depends_on:
      - db
